[workspace]
resolver = "2"

members = [
    "jirascope-core",
    "jirascope-dyn",
    "jirascope-cli",
    "jirascope-test-server",
]

exclude = [
]

# optimize for size
[profile.release]
opt-level = "z"
lto = true
debug = false
