[workspace]
resolver = "2"

members = [
    "jiroscope-core",
    "jiroscope-dyn",
    "jiroscope-cli",
    "jiroscope-test-server",
]

exclude = [
]

# optimize for size
[profile.release]
opt-level = "z"
lto = true
debug = false
