[package]
name = "jiroscope-core"
version = "0.1.0"
edition = "2021"
license = "MIT OR Apache-2.0"

[features]
test_server = []

[dependencies]
ureq = { version = "2.6.2", features = ["json"] }
serde = { version = "1.0", features = ["derive"] }
base64 = "0.21.0"
markdown = "1.0.0-alpha.11"
